spring.application.name=removalsystem
server.port=${SERVER_PORT:8081}
spring.datasource.url=${DB_URL:jdbc:sqlite:${user.home}/removalsystem.db}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false
app.seed.enabled=true
